### ISSUE TITLE
Role hangs in its execution at Rule `3.5.3.2.1` until manually terminated when applied to new Ubuntu VM over SSH

### ISSUE THREAD

**Issue by estenrye** [darkwizard242/cis_ubuntu_2004#5]
# SUMMARY

When running this role from a remote jumpbox, Ansible connection is terminated because Rule `3.5.3.2.1` is applied before applying Rule `3.5.3.2.4`.  

## Rule 3.5.3.2.1

Rule `3.5.3.2.1` configures the default policies for the `INPUT`, `FORWARD` and `OUTPUT` chains to `DROP`.  Because it is applied before Rule `3.5.3.2.4` which applies rules to allow SSH communication it effectively terminates the SSH session being used to apply the role.

https://github.com/darkwizard242/cis_ubuntu_2004/blob/aaccda1ce3c10e599a16d2d751741d0481441496/tasks/section_03.yml#L860-L888

## Rule 3.5.3.2.4

This rule creates iptables rules that allow inbound SSH and outbound DNS requests.  I believe moving its execution before Rule `3.5.3.2.1` would resolve the issue.

https://github.com/darkwizard242/cis_ubuntu_2004/blob/aaccda1ce3c10e599a16d2d751741d0481441496/tasks/section_03.yml#L949-L968

 # ISSUE TYPE

- Bug Report

# ANSIBLE VERSION

```
ansible 2.10.2
  config file = None
  configured module search path = ['/home/esten/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/esten/.local/lib/python3.8/site-packages/ansible
  executable location = /home/esten/.local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

 # STEPS TO REPRODUCE

1. Provision a brand new Ubuntu 20.04 Minimal Server Virtual Machine
2. Apply this role to the new Virtual Machine over SSH.

 # EXPECTED RESULTS

Role should successfully complete execution

 # ACTUAL RESULTS

Role hangs in its execution at Rule `3.5.3.2.1` until manually terminated.

# WORKAROUND

```yaml
- hosts: targets
  roles:
    - darkwizard242.cis_ubuntu_2004
  vars:
    ubuntu_2004_cis_time_synchronization: chrony
    ubuntu_2004_cis_firewall: iptables
    ubuntu_2004_cis_section3_rule_3_5_3_2_1: false
  become: true

- hosts: targets
  roles:
    - darkwizard242.cis_ubuntu_2004
  vars:
    preliminary_appliance: false
    ubuntu_2004_cis_section1: false
    ubuntu_2004_cis_section2: false
    ubuntu_2004_cis_section3: true
    ubuntu_2004_cis_section4: false
    ubuntu_2004_cis_section5: false
    ubuntu_2004_cis_section6: false
    ubuntu_2004_cis_firewall: iptables
  become: true
```
