### ISSUE TITLE
iptables rules are not persisted to disk causing system to fail open on restart

### ISSUE THREAD

**Issue by estenrye** [darkwizard242/cis_ubuntu_2004#9]
# SUMMARY

Iptables Firewall rules are not flushed to disk.  This causes CIS hardening of firewalls to be non-persistent and results in the
machine failing open and accepting all INPUT, FORWARD and OUTPUT traffic.

 # ISSUE TYPE

- Bug Report

# ROLE VERSION

Role Version: 2.0.1

 # STEPS TO REPRODUCE

```yaml
- hosts: default
  become: true
  vars:
    ubuntu_2004_cis_auditd_maxlogfile: 32
    ubuntu_2004_cis_time_synchronization: chrony
    ubuntu_2004_cis_firewall: iptables
    ubuntu_2004_cis_require_ssh_ciphers: aes256-ctr,aes192-ctr,aes128-ctr
    ubuntu_2004_cis_require_ssh_macs: hmac-sha2-256,hmac-sha2-512
    ubuntu_2004_cis_require_ssh_kexalgorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
    ubuntu_2004_cis_require_ssh_allowusers: ubuntu
    ubuntu_2004_cis_require_ssh_allowgroups: ubuntu
    ubuntu_2004_cis_require_ssh_denyusers: bogus
    ubuntu_2004_cis_require_ssh_denygroups: bogus
  tasks:
    - name: Set vagrant usernames in allowed SSH
      ansible.builtin.set_fact:
        ubuntu_2004_cis_require_ssh_allowusers: ubuntu  vagrant
        ubuntu_2004_cis_require_ssh_allowgroups: ubuntu  vagrant
      when:
        - packer_builder_type == "virtualbox-iso"

    - name: execute cis_ubuntu_2004 role
      ansible.builtin.include_role:
        name: darkwizard242.cis_ubuntu_2004
```

 # EXPECTED RESULTS

## Example /etc/iptables/rules.v4 Jinja2 Template

```jinja2
# Ansible Managed - Do Not Edit

*filter

# CIS Ubuntu 1.1.0 3.5.3.2.3 Ensure iptables default deny firewall policy (Automated)
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT DROP [0:0]

# Ensure internal loopback is configured
# CIS Ubuntu 1.1.0 3.5.3.2.1 Ensure iptables loopback traffic is configured (Automated)
-A INPUT  -j ACCEPT -i lo
-A OUTPUT -j ACCEPT -o lo
-A INPUT  -j DROP   -s 127.0.0.0/8

# CIS Ubuntu 1.1.0 3.5.3.2.2 Ensure iptables outbound and established connections are configured (Manual)
-A OUTPUT -j ACCEPT -p tcp  -m conntrack --ctstate NEW,ESTABLISHED
-A OUTPUT -j ACCEPT -p udp  -m conntrack --ctstate NEW,ESTABLISHED
-A OUTPUT -j ACCEPT -p icmp -m conntrack --ctstate NEW,ESTABLISHED
-A INPUT  -j ACCEPT -p tcp  -m conntrack --ctstate NEW,ESTABLISHED
-A INPUT  -j ACCEPT -p udp  -m conntrack --ctstate NEW,ESTABLISHED
-A INPUT  -j ACCEPT -p icmp -m conntrack --ctstate NEW,ESTABLISHED

# CIS Ubuntu 1.1.0 3.5.3.2.4 Ensure iptables firewall rules exist for all open ports (Automated)
-A INPUT  -j ACCEPT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -m comment --comment ssh
-A INPUT  -j ACCEPT -p udp -m udp --dport 123 -m conntrack --ctstate NEW -m comment --comment ntp
{% for rule in firewall_allow_inbound_services_exposed_to_everyone %}
-A INPUT  -j ACCEPT -p {{ rule.protocol }} -m {{ rule.protocol }} --dport {{ rule.port }} -m conntrack --ctstate NEW -m comment --comment "{{ rule.service }}"
{% endfor %}
-A OUTPUT -j ACCEPT -p tcp -m tcp --dport 53 -m conntrack --ctstate NEW -m comment --comment dns
-A OUTPUT -j ACCEPT -p udp -m udp --dport 53 -m conntrack --ctstate NEW -m comment --comment dns
{% for rule in firewall_allow_outbound_requests_to_everyone %}
-A OUTPUT -j ACCEPT -p {{ rule.protocol }} -m {{ rule.protocol }} --dport {{ rule.port }} -m conntrack --ctstate NEW -m comment --comment "{{ rule.service }}"
{% endfor %}
COMMIT

```

## Example /etc/iptables/rules.v6 Jinja2 Template

```jinja2
# Ansible Managed - Do Not Edit

*filter

# CIS Ubuntu 1.1.0 3.5.3.3.3 Ensure ip6tables default deny firewall policy (Automated)
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT DROP [0:0]

# CIS Ubuntu 1.1.0 3.5.3.3.1 Ensure ip6tables loopback traffic is configured (Automated)
-A INPUT  -j ACCEPT -i lo
-A OUTPUT -j ACCEPT -o lo
-A INPUT  -j DROP   -s ::1

# Ensure outbound and established connections are configured
# CIS Ubuntu 1.1.0 3.5.3.3.2 Ensure ip6tables outbound and established connections are configured (Manual)
-A OUTPUT -j ACCEPT -p tcp  -m conntrack --ctstate NEW,ESTABLISHED
-A OUTPUT -j ACCEPT -p udp  -m conntrack --ctstate NEW,ESTABLISHED
-A OUTPUT -j ACCEPT -p icmp -m conntrack --ctstate NEW,ESTABLISHED
-A INPUT  -j ACCEPT -p tcp  -m conntrack --ctstate NEW,ESTABLISHED
-A INPUT  -j ACCEPT -p udp  -m conntrack --ctstate NEW,ESTABLISHED
-A INPUT  -j ACCEPT -p icmp -m conntrack --ctstate NEW,ESTABLISHED

# CIS Ubuntu 1.1.0 3.5.3.3.4 Ensure ip6tables firewall rules exist for all open ports (Automated)
-A INPUT  -j ACCEPT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -m comment --comment ssh
-A INPUT  -j ACCEPT -p udp -m udp --dport 123 -m conntrack --ctstate NEW -m comment --comment ntp
{% for rule in firewall_allow_inbound_services_exposed_to_everyone %}
-A INPUT  -j ACCEPT -p {{ rule.protocol }} -m {{ rule.protocol }} --dport {{ rule.port }} -m conntrack --ctstate NEW -m comment --comment "{{ rule.service }}"
{% endfor %}
-A OUTPUT -j ACCEPT -p tcp -m tcp --dport 53 -m conntrack --ctstate NEW -m comment --comment dns
-A OUTPUT -j ACCEPT -p udp -m udp --dport 53 -m conntrack --ctstate NEW -m comment --comment dns
{% for rule in firewall_allow_outbound_requests_to_everyone %}
-A OUTPUT -j ACCEPT -p {{ rule.protocol }} -m {{ rule.protocol }} --dport {{ rule.port }} -m conntrack --ctstate NEW -m comment --comment "{{ rule.service }}"
{% endfor %}
COMMIT

```

 # ACTUAL RESULTS

## /etc/iptables/rules.v4 After Executing Role

```text
# Generated by iptables-save v1.8.4 on Tue Sep 21 16:43:26 2021
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
# Completed on Tue Sep 21 16:43:26 2021
```

## /etc/iptables/rules.v6 After Executing Role

```text
# Generated by ip6tables-save v1.8.4 on Tue Sep 21 16:43:26 2021
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
# Completed on Tue Sep 21 16:43:26 2021
```

# WORKAROUND

```yaml
- hosts: default
  become: true
  vars:
    ubuntu_2004_cis_auditd_maxlogfile: 32
    ubuntu_2004_cis_time_synchronization: chrony
    ubuntu_2004_cis_firewall: iptables
    ubuntu_2004_cis_require_ssh_ciphers: aes256-ctr,aes192-ctr,aes128-ctr
    ubuntu_2004_cis_require_ssh_macs: hmac-sha2-256,hmac-sha2-512
    ubuntu_2004_cis_require_ssh_kexalgorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
    ubuntu_2004_cis_require_ssh_allowusers: ubuntu
    ubuntu_2004_cis_require_ssh_allowgroups: ubuntu
    ubuntu_2004_cis_require_ssh_denyusers: bogus
    ubuntu_2004_cis_require_ssh_denygroups: bogus
  tasks:
    - name: Set vagrant usernames in allowed SSH
      ansible.builtin.set_fact:
        ubuntu_2004_cis_require_ssh_allowusers: ubuntu  vagrant
        ubuntu_2004_cis_require_ssh_allowgroups: ubuntu  vagrant
      when:
        - packer_builder_type == "virtualbox-iso"

    - name: execute cis_ubuntu_2004 role
      ansible.builtin.include_role:
        name: darkwizard242.cis_ubuntu_2004

    - name: save iptables v4 rules
      ansible.builtin.shell: 
        cmd: iptables-save > /etc/iptables/rules.v4
        warn: false

    - name: save iptables v6 rules
      ansible.builtin.shell:
        cmd: ip6tables-save > /etc/iptables/rules.v6
        warn: false

```
